#allowUnicodeIdentifiers
#boolean, toggles whether unicode identifiers are allowed in names or not, default is false (Default: false)
#apiModulePrefix
#The prefix of the generated ApiModule.
configurationPrefix: Api
#The prefix of the generated Configuration.
#disallowAdditionalPropertiesIfNotPresent
#If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default. (Default: true)
#false - The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
#true - Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.

#ensureUniqueParams
#Whether to ensure parameter names are unique in an operation (rename parameters that are not). (Default: true)

#enumNameSuffix
#Suffix that will be appended to all enum names. (Default: Enum)
#enumPropertyNaming
#Naming convention for enum properties: 'camelCase', 'PascalCase', 'snake_case', 'UPPERCASE', and 'original' (Default: PascalCase)
fileNaming: kebab-case
#Naming convention for the output files: 'camelCase', 'kebab-case'. (Default: camelCase)
#legacyDiscriminatorBehavior
#Set to true for generators with better support for discriminators. (Python, Java, Go, PowerShell, C#have this enabled by default). (Default: true)
#true - The mapping in the discriminator includes descendent schemas that allOf inherit from self and the discriminator mapping schemas in the OAS document.
#false - The mapping in the discriminator includes any descendent schemas that allOf inherit from self, any oneOf schemas, any anyOf schemas, any x-discriminator-values, and the discriminator mapping schemas in the OAS document AND Codegen validates that oneOf and anyOf schemas contain the required discriminator and throws an error if the discriminator is missing.
#modelFileSuffix
#The suffix of the file of the generated model (model<suffix>.ts).
modelPropertyNaming: camelCase
#Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name. Only change it if you provide your own run-time code for (de-)serialization of models (Default: original)
#modelSuffix
#The suffix of the generated model.
#ngVersion
#The version of Angular. (At least 6.0.0) (Default: 11.0.0)
#npmName
#The name under which you want to publish generated npm package. Required to generate a full package
#npmRepository
#Use this property to set an url your private npmRepo in the package.json
#npmVersion
#The version of your npm package. If not provided, using the version from the OpenAPI specification file. (Default: 1.0.0)
#nullSafeAdditionalProps
#Set to make additional properties types declare that their indexer may return undefined (Default: false)
#prependFormOrBodyParameters
#Add form or body parameters to the beginning of the parameter list. (Default: false)
#providedIn
#Use this property to provide Injectables in wanted level (it is only valid in angular version greater or equal to 9.0.0). (Default: root)
#root - The application-level injector in most apps.
#none - No providedIn (same as providedInRoot=false)
#any - Provides a unique instance in each lazy loaded module while all eagerly loaded modules share one instance.
#platform - A special singleton platform injector shared by all applications on the page.
#providedInRoot
#Use this property to provide Injectables in root (it is only valid in angular version greater or equal to 6.0.0). IMPORTANT: Deprecated for angular version greater or equal to 9.0.0, use **providedIn** instead. (Default: false)
#queryParamObjectFormat
#The format for query param objects: 'dot', 'json', 'key'. (Default: dot)
#serviceFileSuffix
#The suffix of the file of the generated service (service<suffix>.ts). (Default: .service)
#serviceSuffix
#The suffix of the generated service. (Default: Service)
#snapshot
#When setting this property to true, the version will be suffixed with -SNAPSHOT.yyyyMMddHHmm (Default: false)
#sortModelPropertiesByRequiredFlag
#Sort model properties to place required parameters before optional parameters. (Default: true)
#sortParamsByRequiredFlag
#Sort method arguments to place required parameters before optional parameters. (Default: true)
#stringEnums
#Generate string enums instead of objects for enum values. (Default: false)
supportsES6: true
#Generate code that conforms to ES6. (Default: false)
#taggedUnions
#Use discriminators to create tagged unions instead of extending interfaces. (Default: false)
#useSingleRequestParameter
#Setting this property to true will generate functions with a single argument containing all API endpoint parameters instead of one argument per parameter. (Default: false)
withInterfaces: true
#Setting this property to true will generate interfaces next to the default class implementations. (Default: false)

