/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Address } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface AddressControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteAddressById
     * 
     * @param addressId addressId
     */
    deleteAddressById(addressId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAddressById
     * 
     * @param addressId addressId
     */
    getAddressById(addressId: number, extraHttpRequestParams?: any): Observable<Address>;

    /**
     * getAllAddresses
     * 
     * @param q q
     * @param sort sort
     */
    getAllAddresses(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Address>>;

    /**
     * saveAddress
     * 
     * @param address address
     */
    saveAddress(address: Address, extraHttpRequestParams?: any): Observable<Address>;

    /**
     * updateAddress
     * 
     * @param address address
     */
    updateAddress(address: Address, extraHttpRequestParams?: any): Observable<Address>;

}
