/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { ApiConfiguration }                                     from '../configuration';



export interface BasicErrorControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * error
     * 
     */
    errorUsingDELETE(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingGET(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingHEAD(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingOPTIONS(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingPATCH(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingPOST(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * error
     * 
     */
    errorUsingPUT(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

}
