/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Category } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface CategoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteCategoryById
     * 
     * @param categoryId categoryId
     */
    deleteCategoryById(categoryId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllCategories
     * 
     * @param q q
     * @param sort sort
     */
    getAllCategories(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Category>>;

    /**
     * getCategoryById
     * 
     * @param categoryId categoryId
     */
    getCategoryById(categoryId: number, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * saveCategory
     * 
     * @param category category
     */
    saveCategory(category: Category, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * updateCategory
     * 
     * @param category category
     */
    updateCategory(category: Category, extraHttpRequestParams?: any): Observable<Category>;

}
