/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { City } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface CityControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteCityById
     * 
     * @param cityId cityId
     */
    deleteCityById(cityId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllCities
     * 
     * @param q q
     * @param sort sort
     */
    getAllCities(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<City>>;

    /**
     * getAllCitiesByCountryId
     * 
     * @param countryId countryId
     */
    getAllCitiesByCountryId(countryId: number, extraHttpRequestParams?: any): Observable<Array<City>>;

    /**
     * getCityByCountryId
     * 
     * @param countryId countryId
     */
    getCityByCountryId(countryId: number, extraHttpRequestParams?: any): Observable<City>;

    /**
     * getCityById
     * 
     * @param cityId cityId
     */
    getCityById(cityId: number, extraHttpRequestParams?: any): Observable<City>;

    /**
     * saveCity
     * 
     * @param city city
     */
    saveCity(city: City, extraHttpRequestParams?: any): Observable<City>;

    /**
     * updateCity
     * 
     * @param city city
     */
    updateCity(city: City, extraHttpRequestParams?: any): Observable<City>;

}
