/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Comment } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface CommentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteCommentById
     * 
     * @param commentId commentId
     */
    deleteCommentById(commentId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllComments
     * 
     * @param q q
     * @param sort sort
     */
    getAllComments(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Comment>>;

    /**
     * getCommentById
     * 
     * @param commentId commentId
     */
    getCommentById(commentId: number, extraHttpRequestParams?: any): Observable<Comment>;

    /**
     * saveComment
     * 
     * @param comment comment
     */
    saveComment(comment: Comment, extraHttpRequestParams?: any): Observable<Comment>;

    /**
     * updateComment
     * 
     * @param comment comment
     */
    updateComment(comment: Comment, extraHttpRequestParams?: any): Observable<Comment>;

}
