/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Order } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface OrderControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteOrderById
     * 
     * @param orderId orderId
     */
    deleteOrderById(orderId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllOrders
     * 
     * @param q q
     * @param sort sort
     */
    getAllOrders(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Order>>;

    /**
     * getOrderById
     * 
     * @param orderId orderId
     */
    getOrderById(orderId: number, extraHttpRequestParams?: any): Observable<Order>;

    /**
     * saveOrder
     * 
     * @param order order
     */
    saveOrder(order: Order, extraHttpRequestParams?: any): Observable<Order>;

    /**
     * updateOrder
     * 
     * @param order order
     */
    updateOrder(order: Order, extraHttpRequestParams?: any): Observable<Order>;

}
