/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Product } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface ProductControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteProductById
     * 
     * @param productId productId
     */
    deleteProductById(productId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllProducts
     * 
     * @param q q
     * @param sort sort
     */
    getAllProducts(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Product>>;

    /**
     * getProductById
     * 
     * @param productId productId
     */
    getProductById(productId: number, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * saveProduct
     * 
     * @param product product
     */
    saveProduct(product: Product, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * updateProduct
     * 
     * @param product product
     */
    updateProduct(product: Product, extraHttpRequestParams?: any): Observable<Product>;

}
