/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductModel } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface ProductModelControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteProductModelById
     * 
     * @param productModelId productModelId
     */
    deleteProductModelById(productModelId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllProductModels
     * 
     * @param q q
     * @param sort sort
     */
    getAllProductModels(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<ProductModel>>;

    /**
     * getProductModelById
     * 
     * @param productModelId productModelId
     */
    getProductModelById(productModelId: number, extraHttpRequestParams?: any): Observable<ProductModel>;

    /**
     * saveProductModel
     * 
     * @param productModel productModel
     */
    saveProductModel(productModel: ProductModel, extraHttpRequestParams?: any): Observable<ProductModel>;

    /**
     * updateProductModel
     * 
     * @param productModel productModel
     */
    updateProductModel(productModel: ProductModel, extraHttpRequestParams?: any): Observable<ProductModel>;

}
