/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductSpecification } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface ProductSpecificationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteProductSpecificationById
     * 
     * @param productSpecificationId productSpecificationId
     */
    deleteProductSpecificationById(productSpecificationId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllProductSpecifications
     * 
     * @param q q
     * @param sort sort
     */
    getAllProductSpecifications(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<ProductSpecification>>;

    /**
     * getProductSpecificationById
     * 
     * @param productSpecificationId productSpecificationId
     */
    getProductSpecificationById(productSpecificationId: number, extraHttpRequestParams?: any): Observable<ProductSpecification>;

    /**
     * saveProductSpecification
     * 
     * @param productSpecification productSpecification
     */
    saveProductSpecification(productSpecification: ProductSpecification, extraHttpRequestParams?: any): Observable<ProductSpecification>;

    /**
     * updateProductSpecification
     * 
     * @param productSpecification productSpecification
     */
    updateProductSpecification(productSpecification: ProductSpecification, extraHttpRequestParams?: any): Observable<ProductSpecification>;

}
