/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProductOrder } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface ProductOrderControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteProductOrderById
     * 
     * @param productOrderId productOrderId
     */
    deleteProductOrderById(productOrderId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllProductOrders
     * 
     * @param q q
     * @param sort sort
     */
    getAllProductOrders(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<ProductOrder>>;

    /**
     * getProductOrderById
     * 
     * @param productOrderId productOrderId
     */
    getProductOrderById(productOrderId: number, extraHttpRequestParams?: any): Observable<ProductOrder>;

    /**
     * saveProductOrder
     * 
     * @param productOrder productOrder
     */
    saveProductOrder(productOrder: ProductOrder, extraHttpRequestParams?: any): Observable<ProductOrder>;

    /**
     * updateProductOrder
     * 
     * @param productOrder productOrder
     */
    updateProductOrder(productOrder: ProductOrder, extraHttpRequestParams?: any): Observable<ProductOrder>;

}
