/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Role } from '../model/models';


import { ApiConfiguration }                                     from '../configuration';



export interface RoleControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: ApiConfiguration;

    /**
     * deleteRoleById
     * 
     * @param roleId roleId
     */
    deleteRoleById(roleId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * getAllRoles
     * 
     * @param q q
     * @param sort sort
     */
    getAllRoles(q?: string, sort?: string, extraHttpRequestParams?: any): Observable<Array<Role>>;

    /**
     * getRoleById
     * 
     * @param roleId roleId
     */
    getRoleById(roleId: number, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * saveRole
     * 
     * @param role role
     */
    saveRole(role: Role, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * updateRole
     * 
     * @param role role
     */
    updateRole(role: Role, extraHttpRequestParams?: any): Observable<Role>;

}
