/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductBrand } from './product-brand';
import { SubCategory } from './sub-category';
import { ProductModel } from './product-model';


export interface Product { 
    createdDate?: string;
    discountPrice?: number;
    ean?: string;
    id?: number;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    name?: string;
    price?: number;
    productBrand?: ProductBrand;
    productModel?: ProductModel;
    recordStatus?: number;
    stock?: number;
    subCategory?: SubCategory;
}

