/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductSpecification { 
    createdDate?: string;
    id?: number;
    key?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    product?: Product;
    recordStatus?: number;
    value?: string;
}

